# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Engineer_AI_Practical' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Engineer_AI_Practical
    pod 'Alamofire'
    pod 'SVProgressHUD'
    pod 'UIScrollView-InfiniteScroll' 

end
